apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-s3-sa
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: test-502
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: test-502-deploy/src/main/resources/apps/test-s3-sa
    repoURL: {{ .Values.spec.repo }}
    targetRevision: {{ .Values.spec.targetRevision }}
    {{ if .Values.spec.helm.valueFiles }}
    helm:
      valueFiles:
        {{- range .Values.spec.helm.valueFiles }}
        - {{ . }}
        {{- end }}
    {{ end }}
  {{- with .Values.spec.syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}