apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-test-sa-app
  namespace: test-502
spec:
  selector:
    matchLabels:
      app: my-test-sa-app

  template:
    metadata:
      labels:
        app: my-test-sa-app

    spec:
      serviceAccountName: test-irsa-502
      containers:
      - name: aws-cli
        image: amazon/aws-cli:latest
        command:
          - sleep
          - "3600"
     
